use super::keyword::Keyword;
use alloc::string::String;

#[derive(Debug, PartialEq)]
pub enum Token<'a> {
    String(String),
    Unicode(String),
    Number(&'a str),
    BigInteger(&'a str),
    Integer(&'a str),
    Float(&'a str),
    Ident(&'a str),
    Keyword(Keyword),
    Period,
    Comma,
    Div,
    Eq,
    Equal,
    Greater,
    GreaterOrEqual,
    Less,
    LessOrEqual,
    Plus,
    Sub,
    Mul,
    Tilde,
    At,
    Sharp,
    Mod,
    Caret,
    Ampersand,
    Pipe,
    QuestionMark,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Eof,
    Colon,
}
